### ISSUE TITLE
不知什么原因的启动错误

### ISSUE THREAD

**Issue by Orisland** [diyigemt/mirai-boot#3]
代码中的汉字均为正确的数值，但是启动后报错，似乎是属性没有写入？
`2021-05-29 17:18:17 I/mirai-boot-status: 
2021-05-29 17:18:17 I/mirai-boot-status: 开始读取配置文件
Exception in thread "main" Cannot create property=miraiboot for JavaBean=ConfigFile(miraiboot=null)
 in 'reader', line 1, column 1:
    miraiboot:
    ^
Cannot create property=logger for JavaBean=ConfigFileMain(bots=[ConfigFileBot(account=我的botqq, password=ConfigFileBotPassword(kind=PLAIN, value=我的botqq密码), configuration=ConfigFileBotConfiguration(protocol=ANDROID_PHONE, device=device.json)), ConfigFileBot(account=123, password=ConfigFileBotPassword(kind=PLAIN, value=pwd), configuration=ConfigFileBotConfiguration(protocol=ANDROID_PHONE, device=device.json))], logger=null, configs=null, alias=null)
 in 'reader', line 2, column 3:
      bots:
      ^
Cannot create property=debug for JavaBean=ConfigFileLogger(network=false, eventStatus=true)
 in 'reader', line 20, column 5:
        network: false # 是否在控制台显示bot的网络信息
        ^
Unable to find property 'debug' on class: net.diyigemt.miraiboot.entity.ConfigFileLogger
 in 'reader', line 22, column 12:
        debug: false # 是否在控制台打印事件解析信息 暂时不起作用
               ^

 in 'reader', line 20, column 5:
        network: false # 是否在控制台显示bot的网络信息
        ^

 in 'reader', line 2, column 3:
      bots:
      ^

	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:291)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.construct(Constructor.java:172)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.construct(Constructor.java:332)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:230)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:220)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:174)
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:158)
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:490)
	at org.yaml.snakeyaml.Yaml.loadAs(Yaml.java:456)
	at net.diyigemt.miraiboot.autoconfig.MiraiApplication.run(MiraiApplication.java:81)
	at test.main(test.java:11)
Caused by: Cannot create property=logger for JavaBean=ConfigFileMain(bots=[ConfigFileBot(account=2687717861, password=ConfigFileBotPassword(kind=PLAIN, value=zhaolong123), configuration=ConfigFileBotConfiguration(protocol=ANDROID_PHONE, device=device.json)), ConfigFileBot(account=123, password=ConfigFileBotPassword(kind=PLAIN, value=pwd), configuration=ConfigFileBotConfiguration(protocol=ANDROID_PHONE, device=device.json))], logger=null, configs=null, alias=null)
 in 'reader', line 2, column 3:
      bots:
      ^
Cannot create property=debug for JavaBean=ConfigFileLogger(network=false, eventStatus=true)
 in 'reader', line 20, column 5:
        network: false # 是否在控制台显示bot的网络信息
        ^
Unable to find property 'debug' on class: net.diyigemt.miraiboot.entity.ConfigFileLogger
 in 'reader', line 22, column 12:
        debug: false # 是否在控制台打印事件解析信息 暂时不起作用
               ^

 in 'reader', line 20, column 5:
        network: false # 是否在控制台显示bot的网络信息
        ^

	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:291)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.construct(Constructor.java:172)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:230)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:220)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:268)
	... 10 more
Caused by: Cannot create property=debug for JavaBean=ConfigFileLogger(network=false, eventStatus=true)
 in 'reader', line 20, column 5:
        network: false # 是否在控制台显示bot的网络信息
        ^
Unable to find property 'debug' on class: net.diyigemt.miraiboot.entity.ConfigFileLogger
 in 'reader', line 22, column 12:
        debug: false # 是否在控制台打印事件解析信息 暂时不起作用
               ^

	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:291)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.construct(Constructor.java:172)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:230)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:220)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:268)
	... 14 more
Caused by: org.yaml.snakeyaml.error.YAMLException: Unable to find property 'debug' on class: net.diyigemt.miraiboot.entity.ConfigFileLogger
	at org.yaml.snakeyaml.introspector.PropertyUtils.getProperty(PropertyUtils.java:158)
	at org.yaml.snakeyaml.introspector.PropertyUtils.getProperty(PropertyUtils.java:148)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.getProperty(Constructor.java:310)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:231)
	... 18 more`

**Comment by diyigemt** [comment]
已经修复  请重新在pom中引入1.0.4的依赖
